# Typical conda environment for a reproducible machine learning project
# Use `mamba env create -f environment.yml`
# or `conda env create -f environment.yml` to install the environment
# Created and maintained by garywei944(garywei944@gmail.com)

name: eden_dev
channels:
  - conda-forge
dependencies:
  - python>=3.14
  - pip>=25.3

  # essential functionality
  - typed-argument-parser
  - httpx
  - atomicwrites
  - pyzipper

  # algorithms
  - networkx

  # system utilities
  - distro

  # tests
  - pytest
  - pytest-asyncio
  - pytest-cov
  - pytest-forked
  - pytest-mock
  - pytest-subtests
  - pytest-xdist

  # development
  - pre-commit
  - identify>=2.6.15
  - black
  - ruff

  # If you need to install pip packages, don't do `pip install xxx`
  # Add the package here and run `mamba env update -f environment.yml --prune`
  # for dependency completeness.
  - pip:
      - sh>=2.2.2
      - py-dagviz
