# Typical conda environment for a reproducible machine learning project
# Use `mamba env create -f environment.yml`
# or `conda env create -f environment.yml` to install the environment
# Created and maintained by garywei944(garywei944@gmail.com)

name: eden
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - pip>=24.0
  - cython

  # essential functionality
  - absl-py
  - attrs
  - ruamel.yaml

  # system utilities
  - distro

  # If you need to install pip packages, don't do `pip install xxx`
  # Add the package here and run `mamba env update -f environment.yml --prune`
  # for dependency completeness.
  - pip:
      - sh
