# Typical conda environment for a reproducible machine learning project
# Use `mamba env create -f environment.yml`
# or `conda env create -f environment.yml` to install the environment
# Created and maintained by garywei944(garywei944@gmail.com)

name: eden_dev
channels:
  - conda-forge
dependencies:
  - python>=3.14
  - pip>=25.3
  - cython

  # essential functionality
  - questionary
  - tabulate
  - rich
  - typer
  - typed-argument-parser

  # OOP utilities
  - attrs

  # meta data
  - ruamel.yaml

  # system utilities
  - distro

  # tests
  - pytest
  - pytest-asyncio
  - pytest-cov
  - pytest-forked
  - pytest-mock
  - pytest-subtests
  - pytest-xdist

  # development
  - pre-commit
  - black
  - ruff

  # If you need to install pip packages, don't do `pip install xxx`
  # Add the package here and run `mamba env update -f environment.yml --prune`
  # for dependency completeness.
  - pip:
      - sh
      - morecontext
