#!/usr/bin/env bash

set -euo pipefail

# This script is POSIX-compliant

LIST=0
INTERACTIVE=0
args=()
while [ "$#" -gt 0 ]; do
    case $1 in
    -l | --list)
        LIST=1
        shift
        ;;
    -i | --interactive)
        INTERACTIVE=1
        shift
        ;;
    *)
        args+=("$1")
        shift
        ;;
    esac
done

log() {
    echo "[eden] $*" >&2
}

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
PROJECT_ROOT="$(realpath "${SCRIPT_DIR}")"

EDEN_HOME="${PROJECT_ROOT}/.eden"
ENV_NAME="eden"

# mamba env
export MAMBA_ROOT_PREFIX="${EDEN_HOME}/micromamba"
export PATH="${MAMBA_ROOT_PREFIX}/bin:${PATH}"

mkdir -p "${MAMBA_ROOT_PREFIX}"

log "MAMBA_ROOT_PREFIX: ${MAMBA_ROOT_PREFIX}"
log "PATH: ${PATH}"

ensure_basics() {
    # ensure curl and procps are installed
    to_install=()

    if ! command_exists ps; then
        if command_exists apt-get; then
            to_install+=("procps")
        elif command_exists pacman; then
            to_install+=("procps-ng")
        fi
    fi
    command_exists curl || to_install+=("curl")
    [ ${#to_install[@]} -eq 0 ] && return

    log "installing basic dependencies: ${to_install[*]}"

    if command_exists apt-get; then
        if [[ "$(id -u)" -eq 0 ]]; then
            apt-get update && apt-get install -y "${to_install[@]}" && rm -rf /var/lib/apt/lists/*
        else
            sudo apt-get update && sudo apt-get install -y "${to_install[@]}" && sudo rm -rf /var/lib/apt/lists/*
        fi
    elif command_exists pacman; then
        if [[ "$(id -u)" -eq 0 ]]; then
            pacman -Sy --noconfirm "${to_install[@]}" && pacman -Scc --noconfirm
        else
            sudo pacman -Sy --noconfirm "${to_install[@]}" && sudo pacman -Scc --noconfirm
        fi
    else
        log "Error: package manager not supported. Please install: ${to_install[*]}"
        exit 1
    fi
}

install_micromamba() {
    if [[ -x "${MAMBA_ROOT_PREFIX}/bin/micromamba" ]]; then
        return
    fi

    log "installing micromamba (silent)"

    BIN_FOLDER="${MAMBA_ROOT_PREFIX}/bin" \
        INIT_YES=no \
        CONDA_FORGE_YES=no \
        "${SHELL}" <(curl -fsSL https://micro.mamba.pm/install.sh) </dev/null
}

init_micromamba() {
    export MAMBA_EXE="${MAMBA_ROOT_PREFIX}/bin/micromamba"
    __mamba_setup="$("$MAMBA_EXE" shell hook --shell bash --root-prefix "${MAMBA_ROOT_PREFIX}" 2>/dev/null)"
    if [[ $? -eq 0 ]]; then
        eval "${__mamba_setup}"
    else
        alias micromamba="${MAMBA_EXE}" # Fallback on help from micromamba activate
    fi
    unset __mamba_setup

    log "initialized micromamba"
}

create_env() {
    if micromamba env list | awk '{print $1}' | grep -qx "${ENV_NAME}"; then
        return
    fi

    log "creating eden environment"
    micromamba create -y -f "${PROJECT_ROOT}/environment.yml"
}

main() {
    ensure_basics
    install_micromamba
    init_micromamba
    create_env

    cd ${PROJECT_ROOT}
    if [[ "${LIST}" -eq 1 ]]; then
        micromamba activate "${ENV_NAME}"
        micromamba list
    elif [[ "${INTERACTIVE}" -eq 1 ]]; then
        log "starting interactive shell in eden environment"
        exec micromamba run -n "${ENV_NAME}" "${SHELL}" -i
    else
        exec micromamba run -n "${ENV_NAME}" python -m eden "$@"
    fi

}

main "${args[@]}"
