#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'

LIST=0
INTERACTIVE=0
args=()
while (($#)); do
    case $1 in
    -l | --list) LIST=1 ;;
    -i | --interactive) INTERACTIVE=1 ;;
    *) args+=("$1") ;;
    esac
    shift
done

log() {
    echo "[eden] $*" >&2
}

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}" && pwd -P)"

EDEN_HOME="${PROJECT_ROOT}/.eden"
ENV_NAME="eden"

# sys env
export DEBIAN_FRONTEND=noninteractive
export USER="${USER:-$(id -un 2>/dev/null || echo unknown)}"

# mamba env
export MAMBA_ROOT_PREFIX="${EDEN_HOME}/micromamba"
export PATH="${MAMBA_ROOT_PREFIX}/bin:${PATH}"

mkdir -p "${MAMBA_ROOT_PREFIX}"

log "MAMBA_ROOT_PREFIX: ${MAMBA_ROOT_PREFIX}"
log "PATH: ${PATH}"

config_sudo() {
    # return if sudo not installed
    command_exists sudo || return 0

    # SUDO
    # https://superuser.com/a/1281228
    # https://github.com/koalaman/shellcheck/wiki/SC2181
    if __sudo="$(sudo -nv 2>&1)"; then
        # has sudo access w/o password
        :
    elif echo "$__sudo" | grep -q '^sudo'; then
        # has sudo access need password

        log "configuring passwordless sudo for current user"

        sudo tee "/etc/sudoers.d/90_${USER}" >/dev/null <<EOF
${USER} ALL=(ALL) NOPASSWD: ALL
EOF
    else
        # no sudo access
        log "warning: no sudo access for current user"
    fi
    unset __sudo
}

ensure_basics() {
    # ensure curl and procps are installed
    to_install=()

    if ! command_exists ps; then
        if command_exists apt-get; then
            to_install+=("procps")
        elif command_exists pacman; then
            to_install+=("procps-ng")
        fi
    fi
    command_exists curl || to_install+=("curl")
    command_exists sudo || to_install+=("sudo")
    [[ ${#to_install[@]} -eq 0 ]] && return

    log "installing basic dependencies: ${to_install[*]}"

    if command_exists apt-get; then
        if [[ "$(id -u)" -eq 0 ]]; then
            apt-get update && apt-get install -y "${to_install[@]}" && rm -rf /var/lib/apt/lists/*
        else
            sudo apt-get update && sudo apt-get install -y "${to_install[@]}" && sudo rm -rf /var/lib/apt/lists/*
        fi
    elif command_exists pacman; then
        if [[ "$(id -u)" -eq 0 ]]; then
            pacman -Sy --noconfirm "${to_install[@]}" && pacman -Scc --noconfirm
        else
            sudo pacman -Sy --noconfirm "${to_install[@]}" && sudo pacman -Scc --noconfirm
        fi
    else
        log "Error: package manager not supported. Please install: ${to_install[*]}"
        exit 1
    fi
}

install_micromamba() {
    [[ -x "${MAMBA_ROOT_PREFIX}/bin/micromamba" ]] && return

    log "installing micromamba (silent)"

    BIN_FOLDER="${MAMBA_ROOT_PREFIX}/bin" \
        INIT_YES=no \
        CONDA_FORGE_YES=no \
        "${SHELL}" <(curl -fsSL https://micro.mamba.pm/install.sh) </dev/null
}

init_micromamba() {
    export MAMBA_EXE="${MAMBA_ROOT_PREFIX}/bin/micromamba"
    __mamba_setup="$("$MAMBA_EXE" shell hook --shell bash --root-prefix "${MAMBA_ROOT_PREFIX}" 2>/dev/null)"
    if [[ $? -eq 0 ]]; then
        eval "${__mamba_setup}"
    else
        alias micromamba="${MAMBA_EXE}" # Fallback on help from micromamba activate
    fi
    unset __mamba_setup

    log "initialized micromamba"
}

create_env() {
    micromamba env list | awk '{print $1}' | grep -qx "${ENV_NAME}" && return

    log "creating eden environment"
    micromamba create -y -f "${PROJECT_ROOT}/environment.yml"
}

main() {
    ensure_basics
    config_sudo
    install_micromamba
    init_micromamba
    create_env

    cd "${PROJECT_ROOT}"
    if ((LIST)); then
        micromamba activate "${ENV_NAME}"
        micromamba list
    elif ((INTERACTIVE)); then
        log "starting interactive shell in eden environment"
        exec micromamba run -n "${ENV_NAME}" "${SHELL}" -i
    else
        exec micromamba run -n "${ENV_NAME}" python -m eden "$@"
    fi

}

main "${args[@]}"
