name: CI

on:
  push:
  pull_request:

jobs:
  e2d_ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image:
          - archlinux:latest
          - debian:10
          - debian:12
          - ubuntu:22.04
          - ubuntu:24.04
        mode:
          - root
          - eva
          - adam
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          docker build \
            --build-arg BASE_IMAGE=${{ matrix.image }} \
            --build-arg MODE=${{ matrix.mode }} \
            -t ci:test ci/

      - name: Run
        run: |
          docker run --rm \
            --user ${{ matrix.mode }} \
            -e MODE=${{ matrix.mode }} \
            ci:test
